<?php
$z[0]=Array("pubdate","",116,159);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",199,242);
$z[1][4]['function']="MyDate('m',@me)";
$z[2]=Array("arcurl","",315,330);
$z[3]=Array("title","",339,353);
$z[4]=Array("title","",355,369);
$z[5]=Array("click","",424,438);
$z[6]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<a href='{@me['arcurl']}'><img src='{@me['big_pic']}'/></a>\"); ",516,669);
$z[6][4]['runphp']="yes";
$z[7]=Array("arcurl","",704,719);
$z[8]=Array("id","",827,860);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("typeurl","",958,974);
$z[10]=Array("typename","",976,993);

?>