<?php
$z[0]=Array("pubdate","",119,162);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",203,246);
$z[1][4]['function']="MyDate('m',@me)";
$z[2]=Array("arcurl","",326,341);
$z[3]=Array("title","",350,364);
$z[4]=Array("title","",366,380);
$z[5]=Array("click","",439,453);
$z[6]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<a href='{@me['\r\n						arcurl']}'><img src='{@me[' big_pic']}' /></a>\"); ",539,702);
$z[6][4]['runphp']="yes";
$z[7]=Array("arcurl","",738,753);
$z[8]=Array("id","",878,911);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("typeurl","",1020,1036);
$z[10]=Array("typename","",1038,1055);

?>