<?php
$z[0]=Array("pubdate","",116,159);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",199,242);
$z[1][4]['function']="MyDate('m',@me)";
$z[2]=Array("arcurl","",319,334);
$z[3]=Array("title","",343,357);
$z[4]=Array("title","",359,373);
$z[5]=Array("click","",432,446);
$z[6]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<a href='{@me['arcurl']}'><img src='{@me['big_pic']}'/></a>\"); ",528,681);
$z[6][4]['runphp']="yes";
$z[7]=Array("arcurl","",716,731);
$z[8]=Array("id","",855,888);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("typeurl","",992,1008);
$z[10]=Array("typename","",1010,1027);

?>