<?php
$z[0]=Array("global","",61,86);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",486,518);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",841,975);
$z[2][4]['row']="8";
$z[2][4]['orderby']="pubdate";
$z[2][4]['titlelen']="50";
$z[3]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",1245,1399);
$z[3][4]['row']="10";
$z[3][4]['col']="1";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="click";
$z[3][4]['typeid']="1,2";
$z[4]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",1482,1634);
$z[4][4]['row']="10";
$z[4][4]['col']="1";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="click";
$z[4][4]['typeid']="3";

?>